FROM zoobab/kind

COPY . .
WORKDIR .


RUN git clone https://github.com/bats-core/bats-core.git && \
    cd bats-core && \
    ./install.sh /usr/local && \
    bats --version

RUN docker version && \
    kind version && \
    kind create cluster && \
    kubectl cluster-info --context kind-kind \

RUN bats e2e.bats