name: Linter

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  Golint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run GoLinter
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--tests=false"